### ISSUE TITLE
Bulk ID lookup

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/sapindale#16]
As part of Archivematica story 81, we need a component that accepts a list of IDs for some database, and then triggers a lookup in that database to determine the existence of documents with those IDs. I suggest we call the component `/src/components/BulkLookup.svelte` and you can set up a test route that imports it. You can test the lookup on the `dipstaging` database, since it's the first one we'll be using, but any couch methods you write should include the database as an argument. 

The IDs will be newline-separated and entered into a `<textarea>`. Clicking a button will, for now, just return the list of IDs, separating IDs that exist in the database with ones that don't.

You'll need to write something in `/src/couch.js` for doing [an `_all_docs` lookup using POST instead of GET](https://docs.couchdb.org/en/1.6.1/api/database/bulk-api.html#post--db-_all_docs).

Eventually the valid IDs will be used to [trigger Couch update functions](https://docs.couchdb.org/en/1.6.1/api/ddoc/render.html#db-design-design-doc-update-update-name-doc-id), but we'll get to that later.

**Comment by RussellMcOrmond** [comment]
Question for @SaschaAdler ,

The current tools try to do a bunch of extra massaging of ID's to go from what staff have wanted to paste into the form and the IDs that are used in the databases.

Examples include a pull-down for the depositor (to prepend in case the ID has no '.' in it), as well as a special pattern for Heritage reels such that T-1234 becomes oocihm.lac_reel_t1234

https://workflow.canadiana.ca/demo/wipFindMoveCreate.html uses a configuration ID for (depositor, search/replace pattern), while https://workflow.canadiana.ca/demo/collectionManage.html has a few hard-coded options (pull-down for depositor, and a checkbox for heritage if 'oocihm' is chosen for depositor).


These are things that can be put into a later project, or they can be looked into now.  You'll want to decide on the timing.   As you can guess I'm a fan of later, but you and Divya may want to speak with Beth, Patty and Natalie (the 3 people likely doing the most ID lookups) to find out what they think.

It might be that this is only important for the tool that will be used for collection and manifest management, which will be looking up slugs.  This may not be relevant for the tool looking up IDs in 'dipstaging' (which is AIP ID's rather than slugs).  I know that these simple patterns won't be useful when we adopt Archivematica as it postpends additional opaque uniqueness to the ID keyed in by the operator.

**Comment by SaschaAdler** [comment]
We could build an option for this component to have a prefix that gets added to every ID prior to the lookup. The simple case of adding a string won't be that hard to do. The idea behind this component is that we can add it to any tool where it would be useful, either on the AIP end or the slug end of things, and so there might be some utility to doing that work now.

As for more complicated cases like the Heritage reel pattern, my long, long-term desire for this (in the access side, anyway) would involve a revamped identifier field that would understand what a LAC reel identifier is and allow for specialized searches for particular reels.

**Comment by SaschaAdler** [comment]
Closed by #18. We included an optional string prefix to prepend to each string. I think further interesting ID mangling should be looked into when we need to.

There's an example of how this works in the master branch; I can create another Docker image if anyone wants to play with it.
